[[headers]]
  for = "*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[build]
  functions = "functions"
  timeout = 300

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

